### ISSUE TITLE
Adding License file

### ISSUE THREAD

**Issue by Murmele** [Technica-Engineering/vector_blf#2]
Hello,

I have seen that the license of the code is GPL3.0+ (https://bestpractices.coreinfrastructure.org/de/projects/145).
Is it possible to add a license file to the repository?

**Comment by kayoub5** [comment]
@Murmele
* there is a LICENSES folder containing a license file
* This repo is a fork of https://bitbucket.org/tobylorenz/vector_blf commits made in this fork were already communicated to the original author in https://bitbucket.org/tobylorenz/vector_blf/issues/38/integrate-bug-fixes-from-fork

**Comment by Murmele** [comment]
@kayoub5 sorry I completely overseen it. Thank you!
